### ISSUE TITLE
As an SBA user, I need to augment my records with SAM information

### ISSUE THREAD

**Issue by kaitlin** [18F/intercessor#10]
Acceptance Criteria:
- [x] Show SAM status in script output
- [x] Include SAM data/identifier in the output file

Tasks:
- [x] Write SAM API integration to pull entity information (in the script that creates the protobuf format)

**Comment by bsweger** [comment]
Notes from Kaitlin: see the Discovery repo for an example 
Get a data.gov API key
Sam API isn't robust--don't make live requests...do one-off data loading and store locally

**Comment by kaitlin** [comment]
contact Nick M. to get the rate limit removed from your data.gov API key

**Comment by kaitlin** [comment]
FYI: django management command from Discovery that imports SAM data: https://github.com/18F/discovery/blob/master/vendor/management/commands/check_sam.py

**Comment by bsweger** [comment]
Note: we're closing this with the knowledge that we might incorporate the API wrapper into the processor as necessary, pending further guidance on vendor validations.
