### ISSUE TITLE
As an agency user, I need an easy-to-read visual representation of the data act schema thus far

### ISSUE THREAD

**Issue by kaitlin** [18F/intercessor#3]
Acceptance Criteria:
- [x] Visual representation already created is updated with the award level information
- [x] The visual representation conveys cardinality in the relationship indicators
- [x] The visual representation makes sense to Neeraj, Renata, Kristina, Aileen, and SBA

Tasks:
- [x] Update existing omnigraffle file with any new information from card #8
- [x] export as png

**Comment by micahsaul** [comment]
Diagram: https://github.com/18F/intercessor/blob/master/schema/data-act-schema.png

**Comment by kaitlin** [comment]
I added a few things to the schema @micahsaul. Can you update the visual when you get a chance?  I added Address.state,  Award.recipientType, changed Award.awardNumber to a string type, and AgencyTransaction.programActivity
