### ISSUE TITLE
As a product owner, I need to see a list (and answers) to research questions to arise during a sprint so that we can keep track of open issues.

### ISSUE THREAD

**Issue by ngupta02** [18F/intercessor#30]
Acceptance Criteria:
- [x]  Add a GitHub label to designate research questions
- [x] All outstanding research questions have a GitHub issue

Tasks:
- [x] Make GitHub issues for all questions in the iPython notebook

**Comment by bsweger** [comment]
We logged these with the [_research questions_](https://github.com/18F/intercessor/labels/research%20questions) label and have been tracking progress on the respective threads:

* https://github.com/18F/intercessor/issues/35
* https://github.com/18F/intercessor/issues/36
* https://github.com/18F/intercessor/issues/34

**Comment by bsweger** [comment]
(note we've added several more research threads, so best way to see everything is going to https://github.com/18F/intercessor/labels/research%20questions)
