### ISSUE TITLE
As an SBA user, I need to understand how my data was mapped to the draft data act schema

### ISSUE THREAD

**Issue by kaitlin** [18F/intercessor#4]
Acceptance Criteria:

- [x] Someone from SBA can confirm that they understand the mapping
- [x] Someone from SBA can comment on the validity of the mapping
- [x]  Either an excel or png exists that an SBA user can read and understand

Tasks:
- [x] Convert programmatic mapping file to csv 
- [x] Create omnigraffle file with visual mapping (if visual)

**Comment by bsweger** [comment]
This is diagrammed here: https://github.com/18F/intercessor/blob/master/assets/images/jaams-prism-data-act-mapping.png

**Comment by bsweger** [comment]
PO_LINE_LOCATIONS_ALL should map to PO_LINES_ALL

**Comment by bsweger** [comment]
Fixed the last thing: #53
