### ISSUE TITLE
As a product owner, I need a draft, award level data act schema

### ISSUE THREAD

**Issue by kaitlin** [18F/intercessor#8]
Acceptance Criteria:

- [x] a technical document exists with all the award level elements 
- [x] the technical doc contains information on the data types of each field and the relationships between fields
- [x] the document has been reviewed by SBA and Treasury team

Tasks:
- [x] Update schema technical docs  to reflect most up to date award level schema (@kaitlin @bsweger @micahsaul)

**Comment by micahsaul** [comment]
Updated schema is here: https://github.com/18F/intercessor/blob/master/schema/data-act-schema.proto

Diagram: https://github.com/18F/intercessor/blob/master/schema/data-act-schema.png

**Comment by bsweger** [comment]
@micahsaul Got some feedback from the SBA folks that they weren't sure how to read this diagram. I think what they really want to see are the specific fields involved with the joins between tables, more like a traditional ERD.

**Comment by bsweger** [comment]
@micahsaul Bumping this in advance of the sprint review. Is it feasible for this to be done, or should we plan for a longer timeline?
